<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE Cartridges[<!ELEMENT Cartridges (Cartridge_list,Cartridge_group)><!ELEMENT Cartridge_list (Cartridge_record*)><!ELEMENT Cartridge_record (Name,Family_name,Group_id,Default?)><!ELEMENT Name (#PCDATA)><!ELEMENT Family_name (#PCDATA)><!ELEMENT Group_id (#PCDATA)><!ELEMENT Default (#PCDATA)><!ELEMENT Cartridge_group (Group_record*)><!ELEMENT Group_record (Group_id,Family_name,Point_300,Point_400)><!ELEMENT Point_300 (#PCDATA)><!ELEMENT Point_400 (#PCDATA)>]>
<Cartridges>
  <Cartridge_list>
    <Cartridge_record>
      <Name>101</Name>
      <Family_name>C105</Family_name>
      <Group_id>0</Group_id>
      <Default>1</Default>
    </Cartridge_record>
    <Cartridge_record>
      <Name>103</Name>
      <Family_name>C105</Family_name>
      <Group_id>0</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>105</Name>
      <Family_name>C105</Family_name>
      <Group_id>0</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>106</Name>
      <Family_name>C105</Family_name>
      <Group_id>0</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>107</Name>
      <Family_name>C105</Family_name>
      <Group_id>0</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>108</Name>
      <Family_name>C105</Family_name>
      <Group_id>0</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>109</Name>
      <Family_name>C105</Family_name>
      <Group_id>0</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>110</Name>
      <Family_name>C105</Family_name>
      <Group_id>0</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>111</Name>
      <Family_name>C105</Family_name>
      <Group_id>0</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>112</Name>
      <Family_name>C105</Family_name>
      <Group_id>0</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>113</Name>
      <Family_name>C105</Family_name>
      <Group_id>0</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>114</Name>
      <Family_name>C105</Family_name>
      <Group_id>0</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>115</Name>
      <Family_name>C105</Family_name>
      <Group_id>0</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>116</Name>
      <Family_name>C105</Family_name>
      <Group_id>0</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>117</Name>
      <Family_name>C105</Family_name>
      <Group_id>0</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>118</Name>
      <Family_name>C105</Family_name>
      <Group_id>0</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>119</Name>
      <Family_name>C105</Family_name>
      <Group_id>0</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>120</Name>
      <Family_name>C105</Family_name>
      <Group_id>0</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>124</Name>
      <Family_name>C105</Family_name>
      <Group_id>0</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>125</Name>
      <Family_name>C105</Family_name>
      <Group_id>0</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>126</Name>
      <Family_name>C105</Family_name>
      <Group_id>0</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>211</Name>
      <Family_name>C105</Family_name>
      <Group_id>0</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>212</Name>
      <Family_name>C105</Family_name>
      <Group_id>0</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>213</Name>
      <Family_name>C105</Family_name>
      <Group_id>0</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>214</Name>
      <Family_name>C105</Family_name>
      <Group_id>0</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>221</Name>
      <Family_name>C105</Family_name>
      <Group_id>0</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>222</Name>
      <Family_name>C105</Family_name>
      <Group_id>0</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>223</Name>
      <Family_name>C105</Family_name>
      <Group_id>0</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>001</Name>
      <Family_name>C120</Family_name>
      <Group_id>1</Group_id>
      <Default>1</Default>
    </Cartridge_record>
    <Cartridge_record>
      <Name>002</Name>
      <Family_name>C120</Family_name>
      <Group_id>1</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>003</Name>
      <Family_name>C120</Family_name>
      <Group_id>2</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>004</Name>
      <Family_name>C120</Family_name>
      <Group_id>1</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>005</Name>
      <Family_name>C120</Family_name>
      <Group_id>1</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>006</Name>
      <Family_name>C120</Family_name>
      <Group_id>1</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>007</Name>
      <Family_name>C120</Family_name>
      <Group_id>2</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>008</Name>
      <Family_name>C120</Family_name>
      <Group_id>2</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>009</Name>
      <Family_name>C120</Family_name>
      <Group_id>1</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>010</Name>
      <Family_name>C120</Family_name>
      <Group_id>1</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>011</Name>
      <Family_name>C120</Family_name>
      <Group_id>1</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>012</Name>
      <Family_name>C120</Family_name>
      <Group_id>1</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>902</Name>
      <Family_name>C120</Family_name>
      <Group_id>1</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>401</Name>
      <Family_name>C130</Family_name>
      <Group_id>1</Group_id>
      <Default>1</Default>
    </Cartridge_record>
    <Cartridge_record>
      <Name>402</Name>
      <Family_name>C130</Family_name>
      <Group_id>2</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>403</Name>
      <Family_name>C130</Family_name>
      <Group_id>2</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>404</Name>
      <Family_name>C130</Family_name>
      <Group_id>2</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>405</Name>
      <Family_name>C130</Family_name>
      <Group_id>3</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>406</Name>
      <Family_name>C130</Family_name>
      <Group_id>3</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>409</Name>
      <Family_name>C130</Family_name>
      <Group_id>3</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>410</Name>
      <Family_name>C130</Family_name>
      <Group_id>3</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>416</Name>
      <Family_name>C130</Family_name>
      <Group_id>3</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>417</Name>
      <Family_name>C130</Family_name>
      <Group_id>3</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>418</Name>
      <Family_name>C130</Family_name>
      <Group_id>3</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>419</Name>
      <Family_name>C130</Family_name>
      <Group_id>3</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>001</Name>
      <Family_name>C210</Family_name>
      <Group_id>1</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>002</Name>
      <Family_name>C210</Family_name>
      <Group_id>1</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>003</Name>
      <Family_name>C210</Family_name>
      <Group_id>2</Group_id>
      <Default>1</Default>
    </Cartridge_record>
    <Cartridge_record>
      <Name>004</Name>
      <Family_name>C210</Family_name>
      <Group_id>2</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>005</Name>
      <Family_name>C210</Family_name>
      <Group_id>2</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>006</Name>
      <Family_name>C210</Family_name>
      <Group_id>2</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>007</Name>
      <Family_name>C210</Family_name>
      <Group_id>2</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>008</Name>
      <Family_name>C210</Family_name>
      <Group_id>2</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>009</Name>
      <Family_name>C210</Family_name>
      <Group_id>1</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>010</Name>
      <Family_name>C210</Family_name>
      <Group_id>1</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>012</Name>
      <Family_name>C210</Family_name>
      <Group_id>2</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>013</Name>
      <Family_name>C210</Family_name>
      <Group_id>2</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>014</Name>
      <Family_name>C210</Family_name>
      <Group_id>1</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>015</Name>
      <Family_name>C210</Family_name>
      <Group_id>2</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>016</Name>
      <Family_name>C210</Family_name>
      <Group_id>2</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>017</Name>
      <Family_name>C210</Family_name>
      <Group_id>2</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>018</Name>
      <Family_name>C210</Family_name>
      <Group_id>2</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>019</Name>
      <Family_name>C210</Family_name>
      <Group_id>2</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>020</Name>
      <Family_name>C210</Family_name>
      <Group_id>1</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>021</Name>
      <Family_name>C210</Family_name>
      <Group_id>2</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>022</Name>
      <Family_name>C210</Family_name>
      <Group_id>2</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>023</Name>
      <Family_name>C210</Family_name>
      <Group_id>1</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>024</Name>
      <Family_name>C210</Family_name>
      <Group_id>2</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>025</Name>
      <Family_name>C210</Family_name>
      <Group_id>2</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>826</Name>
      <Family_name>C210</Family_name>
      <Group_id>0</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>001</Name>
      <Family_name>C245</Family_name>
      <Group_id>2</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>009</Name>
      <Family_name>C245</Family_name>
      <Group_id>3</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>010</Name>
      <Family_name>C245</Family_name>
      <Group_id>3</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>016</Name>
      <Family_name>C245</Family_name>
      <Group_id>3</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>017</Name>
      <Family_name>C245</Family_name>
      <Group_id>3</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>018</Name>
      <Family_name>C245</Family_name>
      <Group_id>3</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>019</Name>
      <Family_name>C245</Family_name>
      <Group_id>3</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>029</Name>
      <Family_name>C245</Family_name>
      <Group_id>1</Group_id>
      <Default>1</Default>
    </Cartridge_record>
    <Cartridge_record>
      <Name>030</Name>
      <Family_name>C245</Family_name>
      <Group_id>1</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>032</Name>
      <Family_name>C245</Family_name>
      <Group_id>1</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>034</Name>
      <Family_name>C245</Family_name>
      <Group_id>2</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>036</Name>
      <Family_name>C245</Family_name>
      <Group_id>1</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>041</Name>
      <Family_name>C245</Family_name>
      <Group_id>2</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>052</Name>
      <Family_name>C245</Family_name>
      <Group_id>3</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>053</Name>
      <Family_name>C245</Family_name>
      <Group_id>3</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>054</Name>
      <Family_name>C245</Family_name>
      <Group_id>3</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>056</Name>
      <Family_name>C245</Family_name>
      <Group_id>3</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>061</Name>
      <Family_name>C245</Family_name>
      <Group_id>3</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>064</Name>
      <Family_name>C245</Family_name>
      <Group_id>2</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>067</Name>
      <Family_name>C245</Family_name>
      <Group_id>3</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>069</Name>
      <Family_name>C245</Family_name>
      <Group_id>4</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>102</Name>
      <Family_name>C245</Family_name>
      <Group_id>3</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>107</Name>
      <Family_name>C245</Family_name>
      <Group_id>3</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>109</Name>
      <Family_name>C245</Family_name>
      <Group_id>1</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>116</Name>
      <Family_name>C245</Family_name>
      <Group_id>3</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>117</Name>
      <Family_name>C245</Family_name>
      <Group_id>3</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>118</Name>
      <Family_name>C245</Family_name>
      <Group_id>3</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>119</Name>
      <Family_name>C245</Family_name>
      <Group_id>3</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>121</Name>
      <Family_name>C245</Family_name>
      <Group_id>1</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>122</Name>
      <Family_name>C245</Family_name>
      <Group_id>2</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>123</Name>
      <Family_name>C245</Family_name>
      <Group_id>3</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>124</Name>
      <Family_name>C245</Family_name>
      <Group_id>3</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>126</Name>
      <Family_name>C245</Family_name>
      <Group_id>1</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>136</Name>
      <Family_name>C245</Family_name>
      <Group_id>1</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>138</Name>
      <Family_name>C245</Family_name>
      <Group_id>1</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>139</Name>
      <Family_name>C245</Family_name>
      <Group_id>1</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>150</Name>
      <Family_name>C245</Family_name>
      <Group_id>3</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>201</Name>
      <Family_name>C245</Family_name>
      <Group_id>2</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>215</Name>
      <Family_name>C245</Family_name>
      <Group_id>4</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>220</Name>
      <Family_name>C245</Family_name>
      <Group_id>4</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>221</Name>
      <Family_name>C245</Family_name>
      <Group_id>3</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>222</Name>
      <Family_name>C245</Family_name>
      <Group_id>3</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>223</Name>
      <Family_name>C245</Family_name>
      <Group_id>3</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>224</Name>
      <Family_name>C245</Family_name>
      <Group_id>4</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>226</Name>
      <Family_name>C245</Family_name>
      <Group_id>3</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>227</Name>
      <Family_name>C245</Family_name>
      <Group_id>3</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>228</Name>
      <Family_name>C245</Family_name>
      <Group_id>3</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>230</Name>
      <Family_name>C245</Family_name>
      <Group_id>0</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>234</Name>
      <Family_name>C245</Family_name>
      <Group_id>2</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>247</Name>
      <Family_name>C245</Family_name>
      <Group_id>3</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>248</Name>
      <Family_name>C245</Family_name>
      <Group_id>3</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>250</Name>
      <Family_name>C245</Family_name>
      <Group_id>4</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>256</Name>
      <Family_name>C245</Family_name>
      <Group_id>3</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>259</Name>
      <Family_name>C245</Family_name>
      <Group_id>3</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>260</Name>
      <Family_name>C245</Family_name>
      <Group_id>3</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>261</Name>
      <Family_name>C245</Family_name>
      <Group_id>3</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>268</Name>
      <Family_name>C245</Family_name>
      <Group_id>3</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>301</Name>
      <Family_name>C245</Family_name>
      <Group_id>4</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>303</Name>
      <Family_name>C245</Family_name>
      <Group_id>3</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>304</Name>
      <Family_name>C245</Family_name>
      <Group_id>3</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>305</Name>
      <Family_name>C245</Family_name>
      <Group_id>3</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>306</Name>
      <Family_name>C245</Family_name>
      <Group_id>4</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>311</Name>
      <Family_name>C245</Family_name>
      <Group_id>2</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>312</Name>
      <Family_name>C245</Family_name>
      <Group_id>2</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>313</Name>
      <Family_name>C245</Family_name>
      <Group_id>2</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>315</Name>
      <Family_name>C245</Family_name>
      <Group_id>4</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>403</Name>
      <Family_name>C245</Family_name>
      <Group_id>3</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>405</Name>
      <Family_name>C245</Family_name>
      <Group_id>3</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>406</Name>
      <Family_name>C245</Family_name>
      <Group_id>3</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>407</Name>
      <Family_name>C245</Family_name>
      <Group_id>3</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>627</Name>
      <Family_name>C245</Family_name>
      <Group_id>3</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>628</Name>
      <Family_name>C245</Family_name>
      <Group_id>3</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>637</Name>
      <Family_name>C245</Family_name>
      <Group_id>1</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>641</Name>
      <Family_name>C245</Family_name>
      <Group_id>0</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>651</Name>
      <Family_name>C245</Family_name>
      <Group_id>3</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>654</Name>
      <Family_name>C245</Family_name>
      <Group_id>3</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>657</Name>
      <Family_name>C245</Family_name>
      <Group_id>0</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>658</Name>
      <Family_name>C245</Family_name>
      <Group_id>0</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>662</Name>
      <Family_name>C245</Family_name>
      <Group_id>0</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>667</Name>
      <Family_name>C245</Family_name>
      <Group_id>3</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>669</Name>
      <Family_name>C245</Family_name>
      <Group_id>3</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>673</Name>
      <Family_name>C245</Family_name>
      <Group_id>2</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>678</Name>
      <Family_name>C245</Family_name>
      <Group_id>3</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>680</Name>
      <Family_name>C245</Family_name>
      <Group_id>0</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>681</Name>
      <Family_name>C245</Family_name>
      <Group_id>0</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>687</Name>
      <Family_name>C245</Family_name>
      <Group_id>0</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>688</Name>
      <Family_name>C245</Family_name>
      <Group_id>0</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>708</Name>
      <Family_name>C245</Family_name>
      <Group_id>3</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>710</Name>
      <Family_name>C245</Family_name>
      <Group_id>2</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>725</Name>
      <Family_name>C245</Family_name>
      <Group_id>3</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>729</Name>
      <Family_name>C245</Family_name>
      <Group_id>3</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>730</Name>
      <Family_name>C245</Family_name>
      <Group_id>3</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>731</Name>
      <Family_name>C245</Family_name>
      <Group_id>2</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>732</Name>
      <Family_name>C245</Family_name>
      <Group_id>3</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>741</Name>
      <Family_name>C245</Family_name>
      <Group_id>3</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>742</Name>
      <Family_name>C245</Family_name>
      <Group_id>2</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>747</Name>
      <Family_name>C245</Family_name>
      <Group_id>1</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>748</Name>
      <Family_name>C245</Family_name>
      <Group_id>1</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>749</Name>
      <Family_name>C245</Family_name>
      <Group_id>1</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>751</Name>
      <Family_name>C245</Family_name>
      <Group_id>3</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>752</Name>
      <Family_name>C245</Family_name>
      <Group_id>3</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>754</Name>
      <Family_name>C245</Family_name>
      <Group_id>3</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>755</Name>
      <Family_name>C245</Family_name>
      <Group_id>3</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>756</Name>
      <Family_name>C245</Family_name>
      <Group_id>3</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>757</Name>
      <Family_name>C245</Family_name>
      <Group_id>3</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>758</Name>
      <Family_name>C245</Family_name>
      <Group_id>3</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>759</Name>
      <Family_name>C245</Family_name>
      <Group_id>2</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>760</Name>
      <Family_name>C245</Family_name>
      <Group_id>4</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>761</Name>
      <Family_name>C245</Family_name>
      <Group_id>3</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>762</Name>
      <Family_name>C245</Family_name>
      <Group_id>4</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>763</Name>
      <Family_name>C245</Family_name>
      <Group_id>3</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>764</Name>
      <Family_name>C245</Family_name>
      <Group_id>1</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>765</Name>
      <Family_name>C245</Family_name>
      <Group_id>3</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>766</Name>
      <Family_name>C245</Family_name>
      <Group_id>3</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>768</Name>
      <Family_name>C245</Family_name>
      <Group_id>3</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>770</Name>
      <Family_name>C245</Family_name>
      <Group_id>3</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>771</Name>
      <Family_name>C245</Family_name>
      <Group_id>1</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>772</Name>
      <Family_name>C245</Family_name>
      <Group_id>1</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>773</Name>
      <Family_name>C245</Family_name>
      <Group_id>2</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>774</Name>
      <Family_name>C245</Family_name>
      <Group_id>2</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>775</Name>
      <Family_name>C245</Family_name>
      <Group_id>3</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>776</Name>
      <Family_name>C245</Family_name>
      <Group_id>3</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>784</Name>
      <Family_name>C245</Family_name>
      <Group_id>3</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>785</Name>
      <Family_name>C245</Family_name>
      <Group_id>2</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>786</Name>
      <Family_name>C245</Family_name>
      <Group_id>0</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>803</Name>
      <Family_name>C245</Family_name>
      <Group_id>2</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>804</Name>
      <Family_name>C245</Family_name>
      <Group_id>2</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>806</Name>
      <Family_name>C245</Family_name>
      <Group_id>2</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>807</Name>
      <Family_name>C245</Family_name>
      <Group_id>3</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>808</Name>
      <Family_name>C245</Family_name>
      <Group_id>3</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>811</Name>
      <Family_name>C245</Family_name>
      <Group_id>3</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>812</Name>
      <Family_name>C245</Family_name>
      <Group_id>3</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>844</Name>
      <Family_name>C245</Family_name>
      <Group_id>3</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>845</Name>
      <Family_name>C245</Family_name>
      <Group_id>3</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>846</Name>
      <Family_name>C245</Family_name>
      <Group_id>3</Group_id>
    </Cartridge_record>
    <Cartridge_record>
      <Name>862</Name>
      <Family_name>C245</Family_name>
      <Group_id>2</Group_id>